import assert from 'node:assert/strict';
import test from 'node:test';

import { ARC_TRUST_BRIEF_COMMENT_MARKER, renderTrustBriefPrComment, upsertTrustBriefPrComment } from '../../lib/github/pr-comment.ts';

function jsonResponse(payload: unknown, status = 200) {
  return {
    ok: status >= 200 && status < 300,
    status,
    async text() { return JSON.stringify(payload); },
    async json() { return payload; },
  };
}

test('renders Trust Brief comment with stable marker for update-in-place behavior', () => {
  const body = renderTrustBriefPrComment('## ARC Trust Brief: Needs Review\n\nCheck scope.');

  assert.match(body, new RegExp(ARC_TRUST_BRIEF_COMMENT_MARKER));
  assert.match(body, /ARC Trust Brief: Needs Review/);
  assert.match(body, /Generated by ARC/);
});

test('creates a PR comment when no prior ARC marker exists', async () => {
  const calls: Array<{ url: string; init?: { method?: string; body?: string } }> = [];
  const fetchFn = async (url: string, init?: { method?: string; body?: string }) => {
    calls.push({ url, init });
    if (calls.length === 1) return jsonResponse([]);
    return jsonResponse({ id: 42 }, 201);
  };

  const result = await upsertTrustBriefPrComment({
    token: 'token',
    repository: 'owner/repo',
    prNumber: 7,
    bodyMarkdown: '## ARC Trust Brief: Pass',
    fetchFn,
  });

  assert.deepEqual(result, { action: 'created', commentId: 42 });
  assert.equal(calls[0].url, 'https://api.github.com/repos/owner/repo/issues/7/comments');
  assert.equal(calls[1].init?.method, 'POST');
  assert.match(calls[1].init?.body ?? '', /arc-trust-brief:v1/);
});

test('updates existing ARC Trust Brief comment instead of creating duplicates', async () => {
  const calls: Array<{ url: string; init?: { method?: string; body?: string } }> = [];
  const fetchFn = async (url: string, init?: { method?: string; body?: string }) => {
    calls.push({ url, init });
    if (calls.length === 1) return jsonResponse([{ id: 99, body: `${ARC_TRUST_BRIEF_COMMENT_MARKER}\nold` }]);
    return jsonResponse({ id: 99 });
  };

  const result = await upsertTrustBriefPrComment({
    token: 'token',
    repository: 'owner/repo',
    prNumber: 7,
    bodyMarkdown: '## ARC Trust Brief: Blocked',
    fetchFn,
  });

  assert.deepEqual(result, { action: 'updated', commentId: 99 });
  assert.equal(calls.length, 2);
  assert.equal(calls[1].url, 'https://api.github.com/repos/owner/repo/issues/comments/99');
  assert.equal(calls[1].init?.method, 'PATCH');
  assert.match(calls[1].init?.body ?? '', /ARC Trust Brief: Blocked/);
});

test('rejects invalid repository and PR input before calling GitHub', async () => {
  await assert.rejects(
    () => upsertTrustBriefPrComment({ token: 'token', repository: 'bad-repo', prNumber: 1, bodyMarkdown: 'x', fetchFn: async () => jsonResponse([]) }),
    /owner\/repo/,
  );
  await assert.rejects(
    () => upsertTrustBriefPrComment({ token: 'token', repository: 'owner/repo', prNumber: 0, bodyMarkdown: 'x', fetchFn: async () => jsonResponse([]) }),
    /positive integer/,
  );
});
