from pathlib import Path
from typing import Optional

import typer

from agent_work_evidence.boundary_evaluator import evaluate_boundaries
from agent_work_evidence.claims import extract_claims, extract_reported_validation, verify_claims
from agent_work_evidence.command_receipts import (
    CommandVerificationError,
    execute_required_commands,
    write_receipt,
)
from agent_work_evidence.contract import ContractError, load_contract
from agent_work_evidence.errors import GitHubCommandError
from agent_work_evidence.gh_client import (
    fetch_pr_checks,
    fetch_pr_commits,
    fetch_pr_diff,
    fetch_pr_files,
    fetch_pr_issue_comments,
    fetch_pr_review_comments,
    fetch_pr_reviews,
    fetch_pr_view,
)
from agent_work_evidence.models import BoundaryFinding, ContextExpansion, ContractEvaluation, EvidenceBrief
from agent_work_evidence.render import render_markdown
from agent_work_evidence.repository_rules import (
    RepositoryRulesError,
    load_repository_rules,
    validate_contract_exceptions,
)
from agent_work_evidence.repo_context import expand_context
from agent_work_evidence.reviewer_concerns import summarize_reviewer_concerns
from agent_work_evidence.risk import assess_risk
from agent_work_evidence.scope import extract_scope_evidence
from agent_work_evidence.trust_brief import (
    build_trust_brief_document,
    render_trust_brief_json,
    render_trust_brief_markdown,
)

app = typer.Typer(help="Create Agent Work Evidence Briefs for GitHub PRs.")


@app.callback()
def main():
    """Create Agent Work Evidence Briefs for GitHub PRs."""


def _operator_addendum_template(repo: str, number: int) -> str:
    return (
        f"# Operator Addendum: {repo}#{number}\n\n"
        "> Human-authored context. This file is not generated by ARC and cannot "
        "change the ARC verdict.\n\n"
        "## Context\n\n"
        "- Add optional operator context here.\n"
    )


def _risk_from_signals(signals):
    if any(signal.level == "high" for signal in signals):
        return "high"
    if any(signal.level == "medium" for signal in signals):
        return "medium"
    return "low"


def _confidence_from_scope_and_gaps(scope, evidence_gaps):
    if scope.status == "clear" and not evidence_gaps:
        return "high"
    if scope.status == "unclear" or len(evidence_gaps) >= 3:
        return "low"
    return "medium"


def _fetch_reviewer_concern_inputs(repo: str, number: int) -> tuple[list[dict], list[str]]:
    raw_items: list[dict] = []
    gaps: list[str] = []
    fetchers = [
        ("PR review comments", fetch_pr_review_comments),
        ("PR issue comments", fetch_pr_issue_comments),
        ("PR submitted reviews", fetch_pr_reviews),
    ]
    for label, fetcher in fetchers:
        try:
            raw_items.extend(fetcher(repo, number))
        except GitHubCommandError as error:
            gaps.append(f"Could not fetch {label}: {error}")
    return raw_items, gaps


FAILURE_LIKE_CHECKS = {"failure", "error", "cancelled", "timed_out", "action_required"}
SUCCESS_LIKE_CHECKS = {"success"}
NEUTRAL_LIKE_CHECKS = {"neutral"}
SKIPPED_LIKE_CHECKS = {"skipped"}
PENDING_LIKE_CHECKS = {"pending", "queued", "in_progress", "requested", "waiting", "expected"}
CHECK_COUNT_ORDER = ["success", "failure", "error", "cancelled", "timed_out", "pending", "skipped", "neutral", "unknown"]


def _normalize_check_state(check: dict) -> str:
    raw = check.get("conclusion") or check.get("state") or check.get("status") or ""
    state = str(raw).strip().lower().replace("-", "_")
    if state in SUCCESS_LIKE_CHECKS:
        return "success"
    if state in FAILURE_LIKE_CHECKS:
        return state
    if state in PENDING_LIKE_CHECKS:
        return "pending"
    if state in SKIPPED_LIKE_CHECKS:
        return "skipped"
    if state in NEUTRAL_LIKE_CHECKS:
        return "neutral"
    if state in {"completed", "complete"}:
        return "unknown"
    return state or "unknown"


def _check_display_name(check: dict) -> str:
    name = str(check.get("name") or check.get("context") or "unnamed check").strip()
    workflow = str(check.get("workflowName") or "").strip()
    if workflow and workflow not in name:
        return f"{workflow} / {name}"
    return name


def _summarize_checks(checks: list[dict]) -> tuple[str | None, list[str], list[str]]:
    if not checks:
        return None, [], []

    deduped: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for check in checks:
        name = _check_display_name(check)
        state = _normalize_check_state(check)
        key = (name, state)
        if key in seen:
            continue
        seen.add(key)
        deduped.append(key)

    counts = {bucket: 0 for bucket in CHECK_COUNT_ORDER}
    for _, state in deduped:
        bucket = state if state in counts else "unknown"
        counts[bucket] += 1

    failed_examples = [f"{name}: {state}" for name, state in deduped if state in FAILURE_LIKE_CHECKS]
    pending_examples = [f"{name}: {state}" for name, state in deduped if state == "pending"]
    green_examples = [
        f"{name}: {state}"
        for name, state in deduped
        if state in {"success", "neutral", "skipped"}
    ]

    rendered_counts = ", ".join(f"{bucket} {count}" for bucket in CHECK_COUNT_ORDER if (count := counts[bucket]))
    summary = [f"CI/check aggregate: {rendered_counts or 'no normalized states'}"]
    if failed_examples:
        summary.append("Failed/error/cancelled checks needing attention: " + "; ".join(failed_examples[:5]))
    if pending_examples:
        summary.append("Pending checks: " + "; ".join(pending_examples[:5]))
    if green_examples:
        summary.append(f"Passing/neutral/skipped checks: {len(green_examples)} total; examples: " + "; ".join(green_examples[:5]))

    if failed_examples:
        aggregate = "failure"
    elif counts["pending"]:
        aggregate = "pending"
    elif deduped and all(state in {"success", "neutral", "skipped"} for _, state in deduped):
        aggregate = "success"
    else:
        aggregate = None
    return aggregate, summary, failed_examples


def _contract_evaluation(
    contract_path: Path | None,
    rules_path: Path | None,
    changed_files: list[str],
    repo_root: Path | None,
    *,
    repository: str = "",
    reviewed_sha: str = "",
    verify_required_commands: bool = False,
    command_timeout_seconds: int = 900,
    receipt_out: Path | None = None,
) -> ContractEvaluation:
    if contract_path is None and rules_path is None:
        return ContractEvaluation(
            verdict="needs_review",
            findings=[
                BoundaryFinding(
                    rule_id="missing_contract",
                    severity="needs_review",
                    message="No frozen ARC contract or repository rules were supplied",
                    evidence=["Use --contract and --rules to enable deterministic boundary checks"],
                )
            ],
        )
    try:
        contract = load_contract(contract_path)
        repository_rules = load_repository_rules(rules_path)
        validate_contract_exceptions(contract, repository_rules)
        command_receipt = None
        command_verification_gap = None
        if verify_required_commands and contract.expected_evidence.required_commands:
            if repo_root is None:
                command_verification_gap = (
                    "Required commands were not executed because no local checkout was provided"
                )
            elif not reviewed_sha:
                command_verification_gap = (
                    "Required commands were not executed because the PR head SHA is unavailable"
                )
            else:
                try:
                    command_receipt = execute_required_commands(
                        repository=repository,
                        repo_root=repo_root,
                        reviewed_sha=reviewed_sha,
                        commands=contract.expected_evidence.required_commands,
                        timeout_seconds=command_timeout_seconds,
                    )
                    if receipt_out is not None:
                        write_receipt(command_receipt, receipt_out)
                except CommandVerificationError as error:
                    command_verification_gap = str(error)
        return evaluate_boundaries(
            contract,
            repository_rules,
            changed_files,
            repo_root=repo_root,
            command_receipt=command_receipt,
            command_verification_gap=command_verification_gap,
        )
    except (ContractError, RepositoryRulesError) as error:
        return ContractEvaluation(
            verdict="blocked",
            findings=[
                BoundaryFinding(
                    rule_id="configuration",
                    severity="blocked",
                    message="ARC contract or repository rules are invalid",
                    evidence=[str(error)],
                )
            ],
        )


@app.command()
def pr(
    repo: str = typer.Argument(..., help="GitHub repo in owner/name format."),
    number: int = typer.Argument(..., help="Pull request number."),
    out: Optional[Path] = typer.Option(None, "--out", "-o", help="Write Markdown brief to this path."),
    repo_root: Optional[Path] = typer.Option(None, "--repo-root", help="Optional local checkout for context expansion."),
    contract_path: Optional[Path] = typer.Option(None, "--contract", help="Frozen ARC assignment contract JSON."),
    rules_path: Optional[Path] = typer.Option(None, "--rules", help="Closed ARC repository rules JSON."),
    verify_required_commands: bool = typer.Option(
        False,
        "--verify-required-commands",
        help="Explicitly execute frozen required commands in the local checkout.",
    ),
    command_timeout_seconds: int = typer.Option(
        900,
        "--command-timeout-seconds",
        min=1,
        help="Timeout for each required command.",
    ),
    receipt_out: Optional[Path] = typer.Option(
        None,
        "--receipt-out",
        help="Optional JSON audit receipt from same-run command execution.",
    ),
    trust_out: Optional[Path] = typer.Option(
        None,
        "--trust-out",
        help="Optional concise ARC-authored Trust Brief Markdown output.",
    ),
    trust_json_out: Optional[Path] = typer.Option(
        None,
        "--trust-json-out",
        help="Optional canonical ARC-authored Trust Brief JSON output.",
    ),
    operator_addendum_out: Optional[Path] = typer.Option(
        None,
        "--operator-addendum-out",
        help="Optional separate human-authored addendum template.",
    ),
):
    """Create an Agent Work Evidence Brief for a GitHub PR."""
    if (contract_path is None) != (rules_path is None):
        raise typer.BadParameter("--contract and --rules must be supplied together")
    if verify_required_commands and contract_path is None:
        raise typer.BadParameter(
            "--verify-required-commands requires --contract and --rules"
        )
    if receipt_out is not None and not verify_required_commands:
        raise typer.BadParameter("--receipt-out requires --verify-required-commands")

    pr_view = fetch_pr_view(repo, number)
    files = fetch_pr_files(repo, number)
    commits = fetch_pr_commits(repo, number)
    diff = fetch_pr_diff(repo, number)
    checks = fetch_pr_checks(repo, number)
    raw_reviewer_concerns, reviewer_concern_gaps = _fetch_reviewer_concern_inputs(repo, number)

    changed_files = [item.get("path", "") for item in files if item.get("path")]
    additions = sum(int(item.get("additions") or 0) for item in files)
    deletions = sum(int(item.get("deletions") or 0) for item in files)
    checks_conclusion, checks_summary, failed_check_examples = _summarize_checks(checks)

    scope = extract_scope_evidence(
        title=pr_view["title"],
        body=pr_view["body"],
        branch=pr_view["branch"],
        commits=commits,
    )
    claims = verify_claims(extract_claims(pr_view["body"]), changed_files=changed_files, diff=diff)
    reported_validation = extract_reported_validation(pr_view["body"])
    risk_signals = assess_risk(
        changed_files=changed_files,
        additions=additions,
        deletions=deletions,
        checks_conclusion=checks_conclusion,
        check_failure_evidence=failed_check_examples,
        diff=diff,
        title=pr_view["title"],
        body=pr_view["body"],
    )

    reviewer_concerns = summarize_reviewer_concerns(raw_reviewer_concerns, gaps=reviewer_concern_gaps)
    context = expand_context(repo_root, changed_files) if repo_root else ContextExpansion(gaps=["No local repo checkout provided; deeper call-site/test context not expanded"])

    evidence_gaps = []
    if not changed_files:
        evidence_gaps.append("No changed files were returned by GitHub")
    if not diff.strip():
        evidence_gaps.append("No diff was returned by GitHub")
    if not checks_summary:
        evidence_gaps.append("No CI/check evidence returned by GitHub")
    contract_evaluation = _contract_evaluation(
        contract_path,
        rules_path,
        changed_files,
        repo_root,
        repository=repo,
        reviewed_sha=pr_view["head_sha"],
        verify_required_commands=verify_required_commands,
        command_timeout_seconds=command_timeout_seconds,
        receipt_out=receipt_out,
    )

    brief = EvidenceBrief(
        repo=repo,
        pr_number=number,
        title=pr_view["title"],
        scope=scope,
        claims=claims,
        changed_files=changed_files,
        checks_summary=checks_summary,
        reported_validation=reported_validation,
        risk_signals=risk_signals,
        reviewer_concerns=reviewer_concerns,
        context=context,
        risk=_risk_from_signals(risk_signals),
        confidence=_confidence_from_scope_and_gaps(scope, evidence_gaps + context.gaps),
        evidence_gaps=evidence_gaps,
        contract_evaluation=contract_evaluation,
    )

    markdown = render_markdown(brief)
    trust_document = build_trust_brief_document(brief)
    if out:
        out.write_text(markdown, encoding="utf-8")
        typer.echo(f"Wrote {out}")
    else:
        typer.echo(markdown)
    if trust_out:
        trust_out.write_text(
            render_trust_brief_markdown(trust_document),
            encoding="utf-8",
        )
        typer.echo(f"Wrote {trust_out}")
    if trust_json_out:
        trust_json_out.write_text(
            render_trust_brief_json(trust_document),
            encoding="utf-8",
        )
        typer.echo(f"Wrote {trust_json_out}")
    if operator_addendum_out:
        operator_addendum_out.write_text(
            _operator_addendum_template(repo, number),
            encoding="utf-8",
        )
        typer.echo(f"Wrote {operator_addendum_out}")


if __name__ == "__main__":
    app()
