export const ARC_TRUST_BRIEF_COMMENT_MARKER = '<!-- arc-trust-brief:v1 -->';

type FetchLike = (url: string, init?: { method?: string; headers?: Record<string, string>; body?: string }) => Promise<{ ok: boolean; status: number; text(): Promise<string>; json(): Promise<unknown> }>;

type GitHubComment = {
  id: number;
  body?: string;
  user?: { type?: string; login?: string };
};

export type UpsertPrCommentInput = {
  token: string;
  repository: string;
  prNumber: number;
  bodyMarkdown: string;
  fetchFn?: FetchLike;
  apiUrl?: string;
};

export type UpsertPrCommentResult = {
  action: 'created' | 'updated';
  commentId: number;
};

export function renderTrustBriefPrComment(markdown: string): string {
  const trimmed = markdown.trim();
  return `${ARC_TRUST_BRIEF_COMMENT_MARKER}\n${trimmed}\n\n---\nGenerated by ARC from the frozen .aiplan, PR diff evidence, and command receipts.`;
}

function parseRepository(repository: string): { owner: string; repo: string } {
  const [owner, repo] = repository.split('/');
  if (!owner || !repo || repository.split('/').length !== 2) throw new Error('repository must be in owner/repo form');
  return { owner, repo };
}

function assertPrNumber(prNumber: number) {
  if (!Number.isInteger(prNumber) || prNumber <= 0) throw new Error('prNumber must be a positive integer');
}

async function readJsonOrThrow(response: Awaited<ReturnType<FetchLike>>, context: string): Promise<unknown> {
  if (response.ok) return response.json();
  const text = await response.text();
  throw new Error(`${context} failed with HTTP ${response.status}${text ? `: ${text}` : ''}`);
}

export async function upsertTrustBriefPrComment(input: UpsertPrCommentInput): Promise<UpsertPrCommentResult> {
  if (!input.token) throw new Error('GitHub token is required');
  assertPrNumber(input.prNumber);
  const { owner, repo } = parseRepository(input.repository);
  const fetchFn = input.fetchFn ?? globalThis.fetch;
  if (!fetchFn) throw new Error('fetch is not available');

  const apiUrl = input.apiUrl ?? 'https://api.github.com';
  const headers = {
    accept: 'application/vnd.github+json',
    authorization: `Bearer ${input.token}`,
    'content-type': 'application/json',
    'x-github-api-version': '2022-11-28',
  };

  const commentsUrl = `${apiUrl}/repos/${owner}/${repo}/issues/${input.prNumber}/comments`;
  const commentsResponse = await fetchFn(commentsUrl, { headers });
  const comments = await readJsonOrThrow(commentsResponse, 'List PR comments');
  if (!Array.isArray(comments)) throw new Error('List PR comments returned a non-array payload');

  const body = renderTrustBriefPrComment(input.bodyMarkdown);
  const existing = (comments as GitHubComment[]).find((comment) => comment.body?.includes(ARC_TRUST_BRIEF_COMMENT_MARKER));

  if (existing?.id) {
    const updateUrl = `${apiUrl}/repos/${owner}/${repo}/issues/comments/${existing.id}`;
    const updateResponse = await fetchFn(updateUrl, { method: 'PATCH', headers, body: JSON.stringify({ body }) });
    await readJsonOrThrow(updateResponse, 'Update ARC Trust Brief comment');
    return { action: 'updated', commentId: existing.id };
  }

  const createResponse = await fetchFn(commentsUrl, { method: 'POST', headers, body: JSON.stringify({ body }) });
  const created = await readJsonOrThrow(createResponse, 'Create ARC Trust Brief comment') as GitHubComment;
  if (!created.id) throw new Error('Create PR comment response did not include an id');
  return { action: 'created', commentId: created.id };
}
